" Common settings
set tabstop=4               " a tab is four spaces
set shiftwidth=4            " number of spaces to use for autoindenting
set expandtab
set autoindent              " always set autoindenting on
set copyindent              " copy the previous indentation on autoindenting
set number                  " always show line numbers
set hlsearch                " highlight search terms
set incsearch               " show search matches as you type
set t_Co=256
let loaded_netrwPlugin = 1  " disable netrw

" Settings derived from vim-sensible plugin
set backspace=indent,eol,start
set ruler
set scrolloff=1
set encoding=utf-8
set autoread
set history=1000

" pathogen settings
execute pathogen#infect()
syntax on
filetype plugin indent on
colorscheme ron

" For more settings, see ~/.vimrc/after/ (AfterColors)

" Vim indent guides settings
"let g:indent_guides_auto_colors = 1
let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_guide_size = 4
let g:indent_guides_auto_colors = 0
" Color value numbers can be found here
" https://vignette.wikia.nocookie.net/vim/images/1/16/Xterm-color-table.png/revision/latest?cb=20110121055231
" Set ctermbg to the color number you want
autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  guibg=green   ctermbg=0
autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=green ctermbg=8

