# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

if [ "$(command -v nc)" != "" ]; then
    alias telnet='nc -v -z $argv'
elif [ "$(command -v ncat)" != ""]; then
    alias telnet='ncat -v --recv-only --idle-timeout 5s $argv'
fi
